# Generated by Django 5.2 on 2025-10-07 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_barkmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barkmodel',
            options={'verbose_name': 'Bark', 'verbose_name_plural': 'Barks'},
        ),
    ]
