name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout student code
        uses: actions/checkout@v3

      - name: Get test binary
        run: |
            timestamp=$(date +%s)
            curl -o cicd_test_binary.tar.gz "https://test-binary.codeling.dev/cicd_test_binary.tar.gz?t=$timestamp" && \
            tar xzf cicd_test_binary.tar.gz && \
            chmod +x cicd_test_binary

      - name: Run tests
        env:
          variant_id: 863f2d9f-8af5-489a-be84-840a7d031aaf
        run: ./cicd_test_binary -command test